# Generated by Django 3.1.7 on 2021-03-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrblog', '0002_auto_20210313_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=130),
        ),
    ]
