# Generated by Django 3.1.7 on 2021-03-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrblog', '0003_auto_20210313_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(default='', max_length=130),
        ),
    ]
