# Generated by Django 3.1.7 on 2021-03-13 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrblog', '0004_auto_20210313_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
