# Generated by Django 3.1.7 on 2021-03-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrblog', '0005_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
    ]
